import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg import sql

APP_DIR = Path(__file__).resolve().parent
SQLITE_DB = Path(
    os.getenv(
        "SQLITE_DB_PATH",
        "/home/crm/data/saudi_sensing_crm.db",
    )
)

PGHOST = os.environ["PGHOST"]
PGUSER = os.environ["PGUSER"]
PGPASSWORD = os.environ["PGPASSWORD"]
PGPORT = int(os.getenv("PGPORT", "5432"))
PGDATABASE = os.getenv("PGDATABASE", "postgres")


def qident(name):
    return sql.Identifier(name)


def pg_connect():
    return psycopg.connect(
        host=PGHOST,
        user=PGUSER,
        password=PGPASSWORD,
        port=PGPORT,
        dbname=PGDATABASE,
        sslmode="require",
    )


def sqlite_tables(con):
    rows = con.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type='table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [r[0] for r in rows]


def sqlite_columns(con, table):
    return con.execute(f'PRAGMA table_info("{table}")').fetchall()


def sqlite_foreign_keys(con, table):
    return con.execute(f'PRAGMA foreign_key_list("{table}")').fetchall()


def sqlite_indexes(con, table):
    indexes = []
    for row in con.execute(f'PRAGMA index_list("{table}")').fetchall():
        # seq, name, unique, origin, partial
        idx_name = row[1]
        unique = bool(row[2])
        if idx_name.startswith("sqlite_autoindex_"):
            continue
        cols = [
            r[2]
            for r in con.execute(f'PRAGMA index_info("{idx_name}")').fetchall()
        ]
        if cols:
            indexes.append((idx_name, unique, cols))
    return indexes


def map_type(sqlite_type):
    t = (sqlite_type or "").upper()
    if "INT" in t:
        return "BIGINT"
    if any(x in t for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in t:
        return "BYTEA"
    return "TEXT"


def translate_default(value):
    if value is None:
        return None
    v = str(value).strip()
    # Most CRM defaults are simple numeric or quoted string defaults.
    if v.upper() in {"NULL", "CURRENT_TIMESTAMP"}:
        return v
    if (v.startswith("'") and v.endswith("'")) or (
        v.startswith('"') and v.endswith('"')
    ):
        return v
    try:
        float(v)
        return v
    except Exception:
        return None


def create_table(pg, sq, table):
    cols = sqlite_columns(sq, table)
    defs = []
    serial_id = None

    for col in cols:
        # cid, name, type, notnull, dflt_value, pk
        _, name, typ, notnull, default, pk = col
        pg_type = map_type(typ)

        if pk and name == "id" and "INT" in (typ or "").upper():
            defs.append(
                sql.SQL("{} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").format(
                    qident(name)
                )
            )
            serial_id = name
            continue

        piece = sql.SQL("{} {}").format(qident(name), sql.SQL(pg_type))
        if pk:
            piece += sql.SQL(" PRIMARY KEY")
        if notnull:
            piece += sql.SQL(" NOT NULL")
        dflt = translate_default(default)
        if dflt is not None:
            piece += sql.SQL(" DEFAULT ") + sql.SQL(dflt)
        defs.append(piece)

    pg.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(qident(table)))
    pg.execute(
        sql.SQL("CREATE TABLE {} ({})").format(
            qident(table),
            sql.SQL(", ").join(defs),
        )
    )
    return serial_id


def copy_table(pg, sq, table):
    cols = [r[1] for r in sqlite_columns(sq, table)]
    if not cols:
        return 0

    rows = sq.execute(
        f'SELECT {", ".join([f"""\"{c}\"""" for c in cols])} FROM "{table}"'
    ).fetchall()

    if rows:
        insert = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            qident(table),
            sql.SQL(", ").join(qident(c) for c in cols),
            sql.SQL(", ").join(sql.Placeholder() for _ in cols),
        )
        pg.executemany(insert, [tuple(r) for r in rows])

    return len(rows)


def create_indexes(pg, sq, table):
    for idx_name, unique, cols in sqlite_indexes(sq, table):
        statement = sql.SQL("CREATE {} INDEX IF NOT EXISTS {} ON {} ({})").format(
            sql.SQL("UNIQUE" if unique else ""),
            qident(idx_name),
            qident(table),
            sql.SQL(", ").join(qident(c) for c in cols),
        )
        pg.execute(statement)


def add_foreign_keys(pg, sq, table):
    for fk in sqlite_foreign_keys(sq, table):
        # id, seq, table, from, to, on_update, on_delete, match
        fk_id, _, ref_table, from_col, to_col, on_update, on_delete, _ = fk
        constraint = f"fk_{table}_{from_col}_{fk_id}"
        statement = sql.SQL(
            "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) "
            "REFERENCES {} ({})"
        ).format(
            qident(table),
            qident(constraint),
            qident(from_col),
            qident(ref_table),
            qident(to_col),
        )
        if on_delete and on_delete.upper() != "NO ACTION":
            statement += sql.SQL(" ON DELETE ") + sql.SQL(on_delete)
        if on_update and on_update.upper() != "NO ACTION":
            statement += sql.SQL(" ON UPDATE ") + sql.SQL(on_update)
        pg.execute(statement)


def reset_identity(pg, table, id_col):
    if not id_col:
        return
    pg.execute(
        sql.SQL(
            """
            SELECT setval(
                pg_get_serial_sequence(%s, %s),
                COALESCE((SELECT MAX({}) FROM {}), 1),
                true
            )
            """
        ).format(qident(id_col), qident(table)),
        (table, id_col),
    )


def main():
    if not SQLITE_DB.exists():
        raise SystemExit(f"SQLite database not found: {SQLITE_DB}")

    sq = sqlite3.connect(SQLITE_DB)
    sq.row_factory = sqlite3.Row

    tables = sqlite_tables(sq)
    print(f"SQLite source: {SQLITE_DB}")
    print(f"Tables found: {len(tables)}")

    with pg_connect() as pg:
        with pg.cursor() as cur:
            # 1. Create tables without foreign keys.
            identity_cols = {}
            for table in tables:
                identity_cols[table] = create_table(cur, sq, table)
                print(f"Created PostgreSQL table: {table}")

            # 2. Copy data.
            total_rows = 0
            for table in tables:
                count = copy_table(cur, sq, table)
                total_rows += count
                print(f"Copied {count} rows: {table}")

            # 3. Recreate indexes.
            for table in tables:
                create_indexes(cur, sq, table)

            # 4. Add foreign keys after all rows exist.
            for table in tables:
                try:
                    add_foreign_keys(cur, sq, table)
                except Exception as exc:
                    print(f"WARNING: foreign keys for {table}: {exc}")

            # 5. Reset identity sequences.
            for table, id_col in identity_cols.items():
                if id_col:
                    try:
                        reset_identity(cur, table, id_col)
                    except Exception as exc:
                        print(f"WARNING: identity reset for {table}: {exc}")

        pg.commit()

    sq.close()
    print(f"Migration complete. Total rows copied: {total_rows}")


if __name__ == "__main__":
    main()
